Sponsor update
xcp-ng/xcp-ng.github.io pull request #8
Opened 2018-04-03 15:04 UTC by Marcpezin

* Adding OpenIt to the list of sponsors
* Adding "joining us" information

2018-04-03 15:10 UTC, olivierlambert requested changes

2018-04-03 15:10 UTC, olivierlambert commented on sponsors.md
> +> Want to join our sponsors? [Contact us](mailto:sales@vates.fr)
we should use "contact@xcp-ng.org" email address instead

2018-04-03 15:13 UTC, Marcpezin commented
done

2018-04-03 15:58 UTC, olivierlambert requested changes

2018-04-03 15:58 UTC, olivierlambert commented on sponsors.md
> +> Want to join our sponsors? [Contact us](mailto:contact@xcp-ng.org)sta
sta?

2018-04-04 07:39 UTC, Marcpezin commented on sponsors.md
> +> Want to join our sponsors? [Contact us](mailto:contact@xcp-ng.org)sta
damn, corrected.

2018-04-04 08:56 UTC, olivierlambert approved these changes

2018-04-04 08:56 UTC, merged